base64 encoded value as string for JSON
TypeError: Object of type 'bytes' is not JSON serializable

the jsonNode() method should return base64 encoded value in form of string instead of byte so that it can be written into a JSON.

import base64
coded_string = b'aGVsbG8='
base64.b64decode(coded_string).decode()