Map functions Updated to reflect changes for Python 3
https://github.com/python/mypy/issues/3940
TypeError: keyword arguments must be strings
bytes in our case.
The base64 encoded values are returned as string datatype instead of bytes.

sorted() is supplied with key to sort the list of dicts.